language: python
python: 3.7
dist: xenial
sudo: true
matrix:
  include:
    - os: linux
      dist: xenial
      python: 3.7
      sudo: true
      before_install:
        - pip install -r requirements-dev.txt
        - python setup.py install
    - os: windows
      language: sh
      python: "3.7"
      env: export PATH="/c/Python37:/c/Python37/Scripts:$PATH"
      before_install:
        - choco install python3
        - pip3 install -r requirements-dev.txt
        - python setup.py install
    - os: osx
      osx_image: xcode10.2
      language: shell
      before_install:
        - pip install -r requirements-dev.txt
        - python setup.py install
script:
    - pytest --cov-config=.coveragerc --cov=pcpartpicker tests/
after_success:
    - coveralls
notifications:
  email:
    recipients:
      - jonathanvusich@gmail.com
    on_success: never
    on_failure: always
