language: python
python: 3.9
dist: xenial
sudo: true
matrix:
  include:
    - os: linux
      dist: xenial
      python: 3.9
      sudo: true
      before_install:
        - pip install -r requirements-dev.txt
        - python setup.py install
script:
    - pytest --cov-config=.coveragerc --cov=pcpartpicker tests/
after_success:
    - coveralls
notifications:
  email:
    recipients:
      - jonathanvusich@gmail.com
    on_success: never
    on_failure: always
