language: python
python: 3.7
dist: xenial
sudo: true
before_install:
    - pip install coveralls
    - pip install -r requirements.txt
    - python setup.py install
script:
    - coverage run --source = pcpartpicker setup.py test
after_success:
    - coveralls
