language: python
python: 3.7
dist: xenial
sudo: true
before_install:
    - pip install pytest pytest-cov
    - pip install coveralls
    - pip install -r requirements.txt
    - python setup.py install
script:
    - py.test --cov
after_success:
    - coveralls
