language: python
python: 3.7
dist: xenial
sudo: true
matrix:
  include:
    - os: linux
      dist: xenial
      python: 3.7
      sudo: true
      before_install:
        - pip install coveralls
        - python setup.py install
    - os: osx
      language: sh
      python: "3.7"
      # Perform the manual steps on osx to install python3 and activate venv
      before_install:
        - brew update
        - brew upgrade python3
        - python3 -m pip install virtualenv
        - virtualenv venv -p python3
        - source venv/bin/activate
        - python3 -m pip install coveralls
        - python3 setup.py install
    - os: windows
      language: sh
      python: "3.7"
      before_install:
        - choco install python3
        - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"
        - python -m pip install coveralls
        - python setup.py install
script:
    - coverage run --source=pcpartpicker -m unittest discover
after_success:
    - coveralls
notifications:
  email:
    recipients:
      - jonathanvusich@gmail.com
    on_success: never
    on_failure: always