brands = {'G-Technology', 'Prestige', 'Plantronics', 'Hannspree', 'SilenX', 'JayBird',
          'Vivo', 'Toshiba', 'Yamaha', 'Favi', 'Gainward', 'Anker', 'Dell', 'TCSunBow', 'Microsoft',
          'Avexir',
          'ACGAM', 'SteelSeries', 'NoiseBlocker', 'Gigabyte', 'Lenovo', 'Tek Republic',
          'Cooltek',
          'Klipsch', 'Trust', 'Zogis', 'Apple', 'Xilence', 'iStarUSA', 'ViewSonic', 'Biostar',
          'Syba',
          'Turtle Beach', 'Thermalright', 'ADATA', 'AllSmartLife', 'Fujitsu',
          'SHARKOON',
          'E-element', 'SolidTek', 'OCZ', 'OcUK', 'TUNIQ', 'VisionTek',
          'Satechi', 'Apple', 'Micron', 'GALAX', 'Turtle Beach', 'BenQ',
          'Raygo',
          'mean:it', '1MORE', 'HP', 'Noctua', 'Planar', 'Super Flower', 'WASD',
          'ID-COOLING', 'SHARKOON', 'SoundMAGIC', 'EVGA', 'Chieftec', 'Altec Lansing',
          'DSI',
          'V7', 'Varmilo', 'APC', 'AMD', 'Avermedia', 'Edimax',
          'Pioneer',
          'Hercules', 'Aula', 'FinalMouse', 'Asus', 'KingDian', 'XFX', 'Fellowes',
          'NVIDIA',
          'X2', 'VisionTek', 'BenQ', 'TUNIQ', 'ECS', 'Delta Electronics',
          'Addlink',
          'Ducky', 'Zowie', 'Inwin', 'PowerColor', 'Gigabyte', 'Marshall', 'Hitachi',
          'Anima', '3M', 'AOC', 'Creative Labs', 'ABS', 'Cubitek', 'Tripp Lite',
          'Xtrfy',
          'XPG', 'NZXT', 'Azza', 'Cooltek', 'Etymotic Research', 'CTL',
          'Athena Power',
          'OcUK', 'Intel', 'CHENBRO', 'Logisys', 'Hcman', 'Hawking Technology', 'Aorus',
          'Genius',
          'I/O Magic', 'Encore', 'Trust', 'Inland', 'VIVO', 'Plugable', 'KeyScan', 'Archgon',
          'Orico', 'Lian-Li', 'Pareema', 'Cyonic', 'Raptor Gaming LK1', 'Eluktronics', 'Intenso',
          'Masscool',
          'ViewEra', 'Unitech', 'PNY', 'Sennheiser', 'Cyborg', 'MS-Tech', 'Lazer3D',
          'Samsung', 'Penclic', 'LaCie', 'Insignia', 'Club', 'Phanteks',
          'Rosewill',
          'Feb Smart', 'SHARKK', 'PC Power', 'CoolMax', 'Qumax', 'HT Omega', 'Linkworld', 'Aorus',
          'Compustocx', 'Kanto', 'Supermicro', 'Tripp Lite', 'LaCie', 'Feenix', 'Supermicro',
          'Trust', 'Gloway', 'Insignia', 'Perixx', 'Lenovo', 'darkFlash', 'MyDigitalSSD',
          'SAMA',
          'iOne', 'QLogic', 'Morex', 'Jonsbo', 'Sceptre', 'Wasabi Mango', 'BlueFinger',
          'Sunbeam',
          'Sahara', 'RAIJINTEK', 'RIOTORO', 'StarTech', 'Philips', 'Maxtor',
          'Smartaudios',
          'IBM', 'Behringer', 'Sparkle', 'Game Max', 'Patriot', 'Mad Catz', 'Ozone Gaming', 'Tecware',
          'Hcman',
          'EVGA', 'XClio', 'Thermalright', 'Cyber Snipa', 'SMK-Link', 'Aerocool',
          'Swiftech', 'Mionix', 'UtechSmart', 'Wintec', 'Tesoro', 'BenQ',
          'Patriot', 'LyxPro', 'Tecware', 'Rottay', 'Func', 'Galaxy',
          'AZIO',
          'Yapster', 'Metallic Gear', 'BFG', 'GranVela', 'Labtec', 'EK', 'Azza',
          'D-Link',
          'Axiom', 'Patriot', 'Deepcool', 'AUKEY', 'KOLINK', 'Cobra', 'Rosewill', 'Diamond',
          'Coby',
          'Speedlink', 'Cisco', 'Panasonic', 'Acer', 'Tacens', 'Leadtek',
          'Motorola', 'Rocketfish', 'AMD', 'DIYPC', 'Scythe', 'Cherry',
          'Behringer', 'Panram', 'Broadway Com Corp', 'MSI', 'LDLC', 'PLDS', 'Denon', 'SK hynix',
          'Nanoxia',
          'Western Digital', 'Max Keyboard', 'Shure', 'BitFenix', 'Inno3D', 'GALAX', 'Astro', 'RCA',
          'Speedlink',
          'AUKEY', 'Gyration', 'Ducky', 'Cougar', 'Buslink', 'Ziotek', 'Jelly Comb',
          'Prolimatech',
          'SeaSonic', 'Iiyama', 'RIOTORO', 'Yamakasi', 'Targus', 'Tracer',
          'PDP',
          'Panasonic', 'Apricom', 'Xion', 'Zowie', 'AvP', 'BFG', 'PrimoChill',
          'Velocifire', 'Eluktro', 'RCA', 'Das Keyboard', 'Wesena', 'Phononic',
          'Element Gaming', 'Imation', 'matias', 'RIOTORO', 'JVC', 'Cisco',
          '3M', 'Orico', 'Transcend', 'Gear Head', 'KUL', 'Adesso', 'Streacom',
          'Syba', 'Fujitsu', 'Sigma', 'Filco', 'FNATIC', 'Eaton', 'G.Skill',
          'Fluance',
          'Rude Gamewear Fierce', 'Compaq', 'Buslink SP-7000-BL', 'Palit', 'Pioneer', 'Insignia NS-PCS20', 'Edge Tech',
          'Plextor', 'Colorful iGame GTX1080Ti', 'Thermaltake', 'Kensington', 'Dynapower', 'Auria EQ276W',
          'Supermicro DVM-TEAC-824B', 'Supermicro HDD-T4000-ST4000NM00', 'Kingston HyperX Alloy', 'Wacom', 'TP-Link',
          'Eizo',
          'G.Skill RIPJAWS', 'Acer Iconia Tab', 'ABS MJ1100-M', 'Titan', 'Ultra', 'Micca', 'iBuypower ARC 647', 'Rii',
          'Corsair Gaming Audio', 'Trust Asto Soundbar', 'FSP Group Windale', 'HG Computers Osmi', 'Tecware Torque RGB',
          'Gigabyte GC-AQC107', 'Azza HURRICANE RGB', 'Jeecoo James Donkey', 'Lite-On', 'Wintec', 'GALAX',
          'Super Talent',
          'Thermal Grizzly', 'NoFan', 'CTA Digital US-UGH', 'Evercool', 'GamerChief HYVE', 'CRYORIG TAKU',
          'HBT+ AXE 140',
          'Parvum Systems', 'Gyration Air Mouse', 'Syba CL-CNL-EOLE802', 'WinPower PSU-401', 'Status Audio',
          'Alpenföhn',
          'V-MODA CROSSFADE', 'Unicomp Ultra Classic', 'Sentey', 'Lenovo', 'Buffalo Technology', 'Audio-Technica',
          'Polk',
          'Alienware', 'Sony SGP-WKB1 Keyboard', 'Apex', 'AZIO', 'Asus ROG', 'SIVGA SVIGA SV007', 'QNIX', 'Team', 'PNY',
          'Microlab', 'Inamax 4332804407', 'TAKSTAR HI-2050', 'ARCTIC', 'Sentey GS-4731', 'Seiki SM40UNP', 'Qisan',
          'AVM FRITZ! WLAN', 'CyberPower', 'Turtle Beach Grip', 'TekNmotion', 'NOX', 'Game Max GM-1050',
          'Kuroutoshikou KRPW-L5-500W/80+', 'Biostar TC-DIAMOND', 'Gelid Solutions', 'KBParadise V60',
          'UtechSmart Saturn',
          'Razer', 'Vortex', 'TeckNet', 'Edifier', 'Logisys', 'JBL', 'V7', 'Biostar iDEQ N10', 'PowerColor',
          'KeyTronic',
          'Thortech', 'Scythe', 'Sakar International Teenage', 'Wooting One', 'HIRALIY HR-F300', 'NOX Krom', 'Fostex',
          'Pixio',
          'Athenatech NE-WN3201D', 'Xigmatek', 'TRENDnet', 'HIS', 'Adesso', 'FSP Group', 'Anidees', 'Swan Speakers',
          'Achieva QH2700-IPSMS', 'Corsair', 'Etekcity Scroll H5GX', 'NEC', 'Deepcool ROCK MASTER', 'Mars Gaming MM1',
          'Topre',
          'NZXT Avatar S', 'Swiftech', 'Chieftec GPS-600A8', 'Corsair TM30', 'Feenix Nascita', 'Tek Republic TM',
          'Belkin',
          'Apevia', 'Sony', 'Netgear', 'Nexus', 'Sony BSP10', 'Mionix', 'Mackie', 'Superlux', 'Reeven', 'Deck',
          'Ergoguys',
          'Saitek', 'SolidTek MS-233BU', 'Crossover', 'Memorex', 'Foxconn', 'Redragon', 'Logitech',
          'Creative Labs Vanguard',
          'Beyerdynamic', 'Gelid Solutions SpeedTouch6', 'G.Skill RIPJAWS MX780', 'BitFenix Recon', 'Sunbeam SEB-2014',
          'Creative Labs', 'Coollaboratory Liquid', 'Tomoko', 'LG', 'Innovation Cooling', 'Cisco N2XX-ABPCI03-M3=',
          'Gear Head 24XDVDINTLS', 'Mars Gaming MC7', 'VIOTEK', 'RAIJINTEK', 'M-Audio', 'LC-Power LC-CF-120-PRO',
          'Zalman',
          'Glorious PC Gaming', 'Acer', 'Cyborg S.T.R.I.K.E. 7', 'X2 ECLIPSE IV', 'Keycool', 'Klevv', 'Phanteks',
          'Silicon Power', 'Bose', 'Jetway', 'HiVi M10', 'HEC', 'Audiovox', 'Diamond', 'Arctic Silver',
          'Swiftpoint Z Gaming',
          'i-rocks', 'CiT', 'JVC', 'AKG', 'Diamond WL700NXS', 'RIOTORO', 'Anidees AI', 'EVGA Z10 (Kailh', 'Kingwin',
          'Fujitsu S26113-E400-L1', 'Zelotes T90', 'Vantec VAF-1225', 'OWC OWCSSD7E6G120', 'Azza',
          'Rude Gamewear RUDE-100',
          'ASRock', 'Gigabyte AORUS ATC700', 'MSI TORX FAN', 'Zotac ZA-MINIKB-BK', 'Wintec FileMate Imagine', 'LEPA',
          'VIVO',
          'Lexar', 'Gateway', 'SanDisk', 'GAMDIAS CHIONE E1A-120R', 'Mars Gaming', 'LC-Power',
          'Enzotech Extreme-X Rev.A',
          'Harman Kardon', 'GE 97986', 'V-Color SKYWALKER PRISM', 'Thermene Graphene', 'EVGA', 'Func HS-260', 'E-Power',
          'Panasonic EJMDA32UK', 'Raidmax', 'IK Multimedia IP-ILOUD-MM-IN', 'Raptor Gaming', 'KFA2 Hall Of',
          'Epic Gear EGMA1H-OB', 'Dynatron', 'Grandtec', 'Anker', 'Koss', 'Athenatech', 'Asus ROG Thor', 'Planar',
          'Syba',
          'IOGEAR GHG700', 'Ingram Micro Jabra', 'Evoluent', 'ATI', 'Powertek PT-eviltek-case100', 'NOX Krom Kyus',
          'Buslink DBW-1647', 'ROCCAT', 'Das Keyboard Division', 'Leopold', 'GAMDIAS TALOS P1', 'SilentiumPC', 'Func',
          'Audioengine', 'Coolink SWiF2-92P', 'Chester Creek Technologies', 'GMMK Glorious Modular', 'Xion', 'Crucial',
          'Enermax', 'GAMDIAS HERMES', 'IBM 40K9200', 'Dell 469-4186', 'Tex Beetle', 'ViewSonic VPAD-CASE-002',
          'ROCCAT ROCC-16003', 'XFX', 'DoubleSight', 'CRYORIG', 'Asus RAIDR EXPRESS', 'Raidmax Cobra 240',
          'AmazonBasics KU-0833 +MSU0939', 'Happy Hacking', 'PreSonus Eris E4.5', 'Cisco XPACC-MSE-G=', 'Turtle Beach',
          'Biwin CSE25A00001-512', 'Hyundai Technology', 'Etekcity', 'Cooler Master', 'Zodiac Aries A-100', 'Kingston',
          'Pyle Audio', 'Cyber Acoustics', 'Motorola Sf200', 'Fractal Design', 'Cubeternet Cubeternet Bluetooth',
          'HiFiMAN',
          'GeIL', 'Apacer', 'ID-COOLING', 'Samsung', 'Monoprice', 'FirePower', 'Jaton', 'Sades', 'Akasa', 'HP',
          'Interlink',
          'Avid Technology DX-992', 'Feenix Autore', 'Zero Infinity Shiva', 'JMAX JX-FM500B', 'Vantec', 'TUNIQ',
          'Freecom',
          'MS-Tech X3 Crow', '1STPLAYER FIRE ROSE', 'EVGA NU', 'Takara Tomy Transformers', 'Avantree', 'Verbatim',
          'IOGEAR',
          'Linksys', 'Bose Companion', 'Aula Killing Soul', 'Polaroid PMI8500', 'Mushkin', 'QNAP QXG-10G1T', 'Drevo',
          'Solid Gear', 'Mars Gaming MFRGBKIT', 'M-Audio Studiophile Q40', 'Skullcandy', 'SHARKOON Skiller Pro',
          'Segotep SG-K8',
          'DLAND', 'Topower', 'HP FH971AA', 'be quiet!', 'KFA2', 'Apotop', 'PPA International 1431v', 'Mistel', 'CFI',
          'Noctua NT-H1', 'DAN Cases', 'Lamptron', 'Nidec Servo D1225C12B6ZPA', 'SIIG', 'Replace Power RP-TFX-420W',
          'Silverstone', 'Seagate', 'HAVIT', 'Naztech i9BT', 'ZEROtherm', 'Antec', 'Patriot Viper V560', 'Spartex OSMI',
          'Key Ovation', 'Yate Loon D12SL-12', 'BitFenix Flo', 'Diablotek', 'Ninox Aurora', 'A4Tech', 'Nixeus',
          'GAMDIAS',
          'Alphacool', 'Nexus NX-5000 R3', 'Netgear GA311', 'Sapphire', 'EagleTec', 'KRK', 'XFX Type-01 Series'}
